added docu for hivemq-swarm integration
hivemq/mqtt-cli pull request #203
Opened 2021-03-15 14:22 UTC by YannickWeber

**Motivation**

**Changes**

2021-03-16 14:27 UTC, gitseti commented on docs/swarm.md
> +has_children: true
```suggestion
has_children: false
```

2021-03-16 14:35 UTC, gitseti commented on docs/swarm.md
> +nav_order: 8
Set this in 
- `logging.md` to 9
- 'configuration.md' to 10

so that Swarm is truly shown as 8. entry.

2021-03-16 14:36 UTC, gitseti commented on docs/swarm.md
> +
```suggestion
```

2021-03-16 14:40 UTC, gitseti commented on docs/swarm.md
> +***
```suggestion
```

2021-03-16 14:41 UTC, gitseti commented on docs/swarm.md
> +***
```suggestion
```

2021-03-16 14:42 UTC, gitseti commented on docs/swarm.md
> +
```suggestion

***

```

2021-03-16 14:45 UTC, gitseti approved these changes
I think the swarm command should also be represented in the `quick-start.md` like the hivemq command.

2021-03-17 07:36 UTC, gitseti commented on docs/quick_start.md
> +* [Swarm](swarm)
```suggestion
* [HiveMQ Swarm](swarm) 
```

2021-03-17 07:38 UTC, gitseti approved these changes

2021-03-17 09:20 UTC, DC2-DanielKrueger approved these changes

2021-03-18 09:51 UTC, A-Imal requested changes

2021-03-18 09:51 UTC, A-Imal commented on docs/swarm.md
> +| ``-r``| ``--run-id`` | Then id of the run to stop. | ``The current run``
```suggestion
| ``-r``| ``--run-id`` | The id of the run to stop. | ``The current run``
```

2021-03-18 11:59 UTC, A-Imal approved these changes

2021-03-18 12:00 UTC, merged